// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/RomanAgaltsev/ya_gophermart/internal/app/gophermart/service/order (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_order_repository.go -package=mocks github.com/RomanAgaltsev/ya_gophermart/internal/app/gophermart/service/order Repository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/RomanAgaltsev/ya_gophermart/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateOrder mocks base method.
func (m *MockRepository) CreateOrder(ctx context.Context, order *model.Order) (*model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", ctx, order)
	ret0, _ := ret[0].(*model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockRepositoryMockRecorder) CreateOrder(ctx, order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockRepository)(nil).CreateOrder), ctx, order)
}

// GetListOfOrders mocks base method.
func (m *MockRepository) GetListOfOrders(ctx context.Context, user *model.User) (model.Orders, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListOfOrders", ctx, user)
	ret0, _ := ret[0].(model.Orders)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetListOfOrders indicates an expected call of GetListOfOrders.
func (mr *MockRepositoryMockRecorder) GetListOfOrders(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListOfOrders", reflect.TypeOf((*MockRepository)(nil).GetListOfOrders), ctx, user)
}
